AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable
  Exclude:
    - "db/schema.rb"
    - "bin/**/*"
    - "node_modules/**/*"
    - "tmp/**/*"
    - "vendor/**/*"

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 20

Metrics/ClassLength:
  Max: 200

Metrics/AbcSize:
  Max: 30

Metrics/BlockLength:
  Max: 30
  Exclude:
    - Rakefile
    - "**/*.rake"
    - spec/**/*.rb
    - config/environments/*.rb
    - config/routes.rb

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/FrozenStringLiteralComment:
  Enabled: true

Style/Documentation:
  Enabled: false

Style/OptionalBooleanParameter:
  Enabled: true

